"""USDM controlled terminology.

Agents never invent a C-code. They choose a *term* from a list this module
offers, and `resolve()` turns that choice into a complete `Code` object. A code
that cannot be resolved is recorded as unresolved and surfaces in the gap report
rather than being quietly fabricated.

Terminology comes from two layers, in order:

1. `USDM_CT.xlsx` -- the DDF controlled terminology published with the standard.
   Authoritative, but it only defines 25 codelists.
2. `ct_supplement.json` -- terms harvested from a known-good reference document
   for the codelists the workbook omits (`StudyEpoch.type`, `StudyArm.type`,
   `InterventionalStudyDesign.model`, and others the eight domains need).
   Generated by `python -m protocol_to_edc.usdm.harvest_ct`; every term keeps its
   provenance.

The same workbook also carries a prose definition for every entity and attribute,
which the OpenAPI schema lacks. `definition()` exposes it, and it is the single
most useful thing to put in a domain prompt.
"""

from __future__ import annotations

import json
import unicodedata
from dataclasses import dataclass
from functools import cache
from pathlib import Path
from typing import Any, Iterable

import openpyxl

from ..core import paths

CODE_SYSTEM = "http://www.cdisc.org"

_VALUE_SHEET = "DDF valid value sets"
_ATTR_SHEET = "DDF Entities&Attributes"
_VALUE_HEADER_ROW = 6


class TerminologyError(KeyError):
    """A codelist that is not known to any terminology layer."""


@dataclass(frozen=True)
class Term:
    """One coded value."""

    code: str
    decode: str
    definition: str = ""
    codelist_code: str = ""
    extensible: bool = False
    source: str = "USDM_CT"

    def as_code(self, version: str) -> dict[str, Any]:
        """Render as a USDM `Code` object (without an id -- the assembler adds it)."""
        return {
            "code": self.code,
            "codeSystem": CODE_SYSTEM,
            "codeSystemVersion": version,
            "decode": self.decode,
            "instanceType": "Code",
        }


def _norm(text: str) -> str:
    """Fold a decode for matching: case, accents, punctuation and spacing."""
    folded = unicodedata.normalize("NFKD", str(text))
    folded = "".join(c for c in folded if not unicodedata.combining(c))
    keep = [c.lower() if c.isalnum() else " " for c in folded]
    return " ".join("".join(keep).split())


@dataclass(frozen=True)
class Codelist:
    entity: str
    attribute: str
    terms: tuple[Term, ...]
    extensible: bool = False

    @property
    def key(self) -> str:
        return f"{self.entity}.{self.attribute}"

    def find(self, decode: str) -> Term | None:
        """Match a decode exactly, then loosely. Returns None if nothing matches."""
        target = _norm(decode)
        if not target:
            return None
        for term in self.terms:
            if _norm(term.decode) == target:
                return term
        for term in self.terms:
            a, b = _norm(term.decode), target
            if a.startswith(b) or b.startswith(a):
                return term
        return None

    def render(self, *, limit: int = 40) -> str:
        """Offer the permitted values to an agent, decode only -- never the code."""
        shown = self.terms[:limit]
        lines = [f"{self.key} -- permitted values:"]
        for term in shown:
            summary = term.definition.split(". ")[0][:110] if term.definition else ""
            lines.append(f"  - {term.decode}" + (f" : {summary}" if summary else ""))
        if len(self.terms) > limit:
            lines.append(f"  ... and {len(self.terms) - limit} more")
        if self.extensible:
            lines.append(
                "  This codelist is extensible: if none fits, give the closest "
                "wording from the protocol and it will be flagged for review."
            )
        return "\n".join(lines)


class Terminology:
    """Loaded terminology for one USDM version."""

    def __init__(
        self,
        version: str,
        codelists: dict[str, Codelist],
        definitions: dict[str, str],
        ct_version: str,
    ) -> None:
        self.version = version
        self.ct_version = ct_version
        self._codelists = codelists
        self._definitions = definitions

    # -- lookup ------------------------------------------------------------

    def keys(self) -> tuple[str, ...]:
        return tuple(sorted(self._codelists))

    def has(self, entity: str, attribute: str) -> bool:
        return f"{entity}.{attribute}" in self._codelists

    def codelist(self, entity: str, attribute: str) -> Codelist:
        try:
            return self._codelists[f"{entity}.{attribute}"]
        except KeyError:
            raise TerminologyError(
                f"No codelist for {entity}.{attribute} in USDM {self.version} "
                "terminology. Harvest it or treat the value as sponsor-defined."
            ) from None

    def definition(self, entity: str, attribute: str | None = None) -> str:
        """Prose definition of an entity or one of its attributes; '' if unknown."""
        key = entity if attribute is None else f"{entity}.{attribute}"
        return self._definitions.get(key, "")

    # -- resolution --------------------------------------------------------

    def resolve(self, entity: str, attribute: str, decode: str) -> dict[str, Any] | None:
        """Turn an agent's chosen decode into a `Code`, or None if unresolvable."""
        if not decode:
            return None
        try:
            codelist = self.codelist(entity, attribute)
        except TerminologyError:
            return None
        term = codelist.find(decode)
        return term.as_code(self.ct_version) if term else None

    def sponsor_code(self, decode: str) -> dict[str, Any]:
        """A sponsor-defined fallback code, clearly marked as not CDISC terminology."""
        return {
            "code": _norm(decode).upper().replace(" ", "_")[:64] or "UNSPECIFIED",
            "codeSystem": "SPONSOR",
            "codeSystemVersion": "1",
            "decode": decode,
            "instanceType": "Code",
        }

    # -- prompt rendering --------------------------------------------------

    def render(self, keys: Iterable[str]) -> str:
        blocks = []
        for key in keys:
            entity, _, attribute = key.partition(".")
            if self.has(entity, attribute):
                blocks.append(self.codelist(entity, attribute).render())
        return "\n\n".join(blocks)


def _load_workbook_layer(path: Path) -> tuple[dict[str, Codelist], dict[str, str]]:
    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)

    definitions: dict[str, str] = {}
    if _ATTR_SHEET in wb.sheetnames:
        ws = wb[_ATTR_SHEET]
        header = None
        for row in ws.iter_rows(values_only=True):
            if header is None:
                if row and row[0] == "Row #":
                    header = {str(v): i for i, v in enumerate(row) if v}
                continue
            entity = row[header["Entity Name"]]
            role = row[header["Role"]]
            name = row[header["Logical Data Model Name"]]
            definition = row[header["Definition"]]
            if not entity or not definition:
                continue
            key = str(entity) if role == "Entity" else f"{entity}.{name}"
            definitions.setdefault(key, str(definition).strip())

    grouped: dict[str, list[Term]] = {}
    extensible: dict[str, bool] = {}
    codelist_codes: dict[str, str] = {}
    if _VALUE_SHEET in wb.sheetnames:
        ws = wb[_VALUE_SHEET]
        for row in ws.iter_rows(min_row=_VALUE_HEADER_ROW + 1, values_only=True):
            if not row or not row[1] or not row[2]:
                continue
            entity, attribute = str(row[1]).strip(), str(row[2]).strip()
            code, decode = row[5], row[6]
            if not code or not decode:
                continue
            key = f"{entity}.{attribute}"
            grouped.setdefault(key, []).append(
                Term(
                    code=str(code).strip(),
                    decode=str(decode).strip(),
                    definition=str(row[8]).strip() if len(row) > 8 and row[8] else "",
                    codelist_code=str(row[3]).strip() if row[3] else "",
                    extensible=str(row[4]).strip().lower() == "yes",
                )
            )
            extensible[key] = str(row[4]).strip().lower() == "yes"
            codelist_codes[key] = str(row[3]).strip() if row[3] else ""
    wb.close()

    codelists = {}
    for key, terms in grouped.items():
        entity, _, attribute = key.partition(".")
        codelists[key] = Codelist(
            entity=entity,
            attribute=attribute,
            terms=tuple(sorted(terms, key=lambda t: t.decode)),
            extensible=extensible.get(key, False),
        )
    return codelists, definitions


def _load_supplement_layer(path: Path) -> dict[str, Codelist]:
    if not path.is_file():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    out: dict[str, Codelist] = {}
    for key, entry in data.get("codelists", {}).items():
        entity, _, attribute = key.partition(".")
        terms = tuple(
            Term(
                code=t["code"],
                decode=t["decode"],
                definition=t.get("definition", ""),
                source=entry.get("source", "harvested"),
                extensible=True,
            )
            for t in entry.get("terms", [])
        )
        if terms:
            out[key] = Codelist(
                entity=entity, attribute=attribute, terms=terms, extensible=True
            )
    return out



@cache
def load(version: str = "4.0.0") -> Terminology:
    """Load and cache terminology for a USDM version."""
    directory = paths.usdm_resource_dir(version)
    workbook = directory / "USDM_CT.xlsx"
    if not workbook.is_file():
        raise FileNotFoundError(f"USDM controlled terminology not found at {workbook}")

    codelists, definitions = _load_workbook_layer(workbook)

    supplement_path = directory / "ct_supplement.json"
    supplement = _load_supplement_layer(supplement_path)
    # The published workbook wins wherever the two overlap.
    for key, codelist in supplement.items():
        codelists.setdefault(key, codelist)

    ct_version = "2024-09-27"
    if supplement_path.is_file():
        meta = json.loads(supplement_path.read_text(encoding="utf-8"))
        ct_version = meta.get("codeSystemVersion", ct_version)

    return Terminology(version, codelists, definitions, ct_version)
